apiVersion: data.mycompany.io/v1alpha1
kind: SparkSqlPipeline
metadata:
  name: cash-pipeline
  namespace: dev
spec:
  image: spark-s3a:4.0.1
  imagePullPolicy: IfNotPresent
  sparkVersion: "4.0.1"

  storage:
    type: azure
    azure:
      accountName: "sparkpipelinesadls"
      accountKeySecret: "azure-credentials"
      appConfigMap: "app-config"
      scriptsContainer: "scripts"

  driver:
    cores: 1
    memory: "512m"
    serviceAccount: team-a-spark

  executor:
    cores: 1
    instances: 1
    memory: "512m"

  steps:
    - id: team-a
      input: "abfss://raw@sparkpipelinesadls.dfs.core.windows.net/cash/"
      output: "abfss://lake@sparkpipelinesadls.dfs.core.windows.net/cash/"
      sql: "abfss://scripts@sparkpipelinesadls.dfs.core.windows.net/cash_transform.sql"
      inputFormat: csv
      outputFormat: parquet
      partitionColumn: date